databases:
  - name: recipe
    databaseName: recipe_c89l
    user: recipe_c89l_user

services:
  - type: web
    name: recipe-app-girma
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false